### ISSUE TITLE
delta.grad is None after backward

### ISSUE THREAD

**Issue by pzs19** [locuslab/smoothinv#1]
Great work! But when I run your code, delta.grad is None after backward in SmoothInv().synthesize(), thus blocked here https://github.com/locuslab/smoothinv/blob/228db4c681f2ca231c7417a6e4064c9b6f09d1ae/smoothinv.py#L59.

**Comment by pzs19** [comment]
no-diffusion, trojai

**Comment by Eric-mingjie** [comment]
Thanks a lot for your interest in our code and pointing out this issue.

If you are using smoothinv with diffusion, there is a bug I just recognized in my code (this is my bad). Here it should be set to `torch.enable_grad()` in this [line](https://github.com/locuslab/smoothinv/blob/228db4c681f2ca231c7417a6e4064c9b6f09d1ae/DRM.py#L123). Hope this solves your problem.
